---
- hosts: web
  name: configuration play
  user: ubuntu

  # snippet taken from  https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f#gistcomment-1914049
  # we don't need to gather facts since system is known
  gather_facts: false
  pre_tasks:
    - name: Install python for Ansible
      become: true
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false
    - setup: # aka gather_facts

  tasks:

    - name: Install nginx
      become: true
      apt:
        name: nginx
        update_cache: true

#Following steps on https://docs.docker.com/install/linux/docker-ce/ubuntu/
    - name: Install docker dependencies
      become: true
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - 'ca-certificates'
        - 'apt-transport-https'
        - 'software-properties-common'
        - 'curl'
        - 'linux-image-extra-3.13.0-106-generic'
        - 'linux-image-extra-virtual'

#Recommended by the Docker docs but we aren't fully verifying the key.
    - name: Add docker gpg key
      apt_key:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
        id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
        state: present
      register: 'add_reposity_key'
      ignore_errors: true

    - name: Add docker repo to apt
      become: true
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
        update_cache: yes

    - name: Install docker
      become: true
      apt:
        pkg: docker-ce # can give a specific version here
        state: present
        update_cache: yes

# enable systemd so service starts on boot
    - name: Enable systemd service
      service:
        name: 'docker'
        state: started
        enabled: yes
